services:
  db:
    image: mysql:8.0
    container_name: bookreviews-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_reviews
      MYSQL_USER: book_user
      MYSQL_PASSWORD: book_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    container_name: bookreviews-api
    depends_on:
      - db
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MySql: "Server=db;Port=3306;Database=book_reviews;Uid=book_user;Pwd=book_pass;"
      JwtSettings__SecretKey: "pon_aqui_un_valor_seguro"
      JwtSettings__Issuer: "bookreviews-api"
      JwtSettings__Audience: "bookreviews-client"
    ports:
      - "8080:80"

volumes:
  db_data:
